### ISSUE TITLE
Wrong return value

### ISSUE THREAD

**Issue by DariusIII** [voku/simple_html_dom#30] opened 2019-04-01 10:42 UTC
After update to latest version i am getting this error:

`Return value of voku\helper\HtmlDomParser::findOne() must be an instance of voku\helper\SimpleHtmlDom, instance of voku\helper\SimpleHtmlDomNodeBlank returned`

Probably a missed change in core?

**Comment by voku** [comment] 2019-04-02 00:28
Can you show me a minimal example for this problem?

**Comment by DariusIII** [comment] 2019-04-02 01:36
Sure i can.

public function find:

https://github.com/voku/simple_html_dom/blob/master/src/voku/helper/HtmlDomParser.php#L692

`@return SimpleHtmlDom|SimpleHtmlDom[]|SimpleHtmlDomNodeInterface`

And function findOne:

https://github.com/voku/simple_html_dom/blob/master/src/voku/helper/HtmlDomParser.php#L667

`* @return SimpleHtmlDom`

Some related functions also do not return correct value:

https://github.com/voku/simple_html_dom/blob/master/src/voku/helper/HtmlDomParser.php#L580

`public function getElementById`

**Comment by voku** [comment] 2019-04-25 23:17
Sorry for the late response, I have fixed return types in version 4.5.0. Now we use interfaces instead of concrete classes, so that we can return different classes.

PS: can you show anyway a minimal example for this problem via a small html input example? So that I can add your example into the tests? Thanks!

**Comment by Lednerb** [comment] 2019-05-20 07:38
Hey @voku 

I've just had the same problem and found this issue.

That's a simple code snippet, that was affected by the issue:

```
$dom = HtmlDomParser::str_get_html($response->getBody()->getContents());
$tag = $dom->findOne('meta[name="myToken"]');
```

With the `$response` having a HTTP Status 200 and no contents.

Error message was:

`TypeError: Return value of voku\helper\HtmlDomParser::findOne() must be an instance of voku\helper\SimpleHtmlDom, instance of voku\helper\SimpleHtmlDomNodeBlank returned`

I can approve that the issue is fixed in the latest version.

**Comment by voku** [comment] 2019-05-20 07:59
@Lednerb I added a test for your example and it passed without any error or warning (https://github.com/voku/simple_html_dom/commit/ebc63c36dc75a350c390b51f0fc134daa469adda) ... maybe you need to update to the new version?

**Comment by Lednerb** [comment] 2019-05-20 08:31
> @Lednerb I added a test for your example and it passed without any error or warning ([ebc63c3](https://github.com/voku/simple_html_dom/commit/ebc63c36dc75a350c390b51f0fc134daa469adda)) ... maybe you need to update to the new version?

> I can approve that the issue is fixed in the latest version.

Sure, everything works fine for me, but you've asked for a small input example to add the tests in https://github.com/voku/simple_html_dom/issues/30#issuecomment-486871023 so I've sent mine ;)

Thanks for the great work again!

**Comment by voku** [comment] 2019-05-20 10:40
😋 Ok l, understand... thanks for the feedback.

**Closed** 2019-05-20 11:26 UTC
